---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Reload Apache
  service:
    name: apache2
    state: reloaded

- name: Restart Apache
  service:
    name: apache2
    state: restarted
