---
apache_user: www-data
apache_group: www-data
apache_service: apache2
apache_server_root: /etc/apache2


__apache_packages:
  - build-essential 
  - libssl-dev
  - libexpat1-dev
  - libpcre3-dev
  - libapr1-dev
  - libaprutil1-dev

__lamp_packages:
  - python3-pymysql
  - php
  - php-mysql
  - libapache2-mod-php

__php_modules:
  - php-curl
  - php-gd
  - php-mbstring
  - php-xml
  - php-xmlrpc
  - php-soap
  - php-intl
  - php-zip
