---

# Setup WordPress Stack packages

- name: Install dependencies packages
  include_tasks: "setup-{{ ansible_os_family }}.yml"
  tags: [system]

# Apache configuration

- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: '0755'
  tags: [apache]

- name: Create conf.d/ directory
  ansible.builtin.file:
    path: "{{ apache_server_root }}/conf.d"
    state: directory
    mode: '0755'
  tags: [apache]

- name: Ensure conf.d/*.conf is included in apache main config
  lineinfile:
    path: "{{ apache_main_conf }}"
    insertafter: EOF
    line: "IncludeOptional conf.d/*.conf"
    state: present
  notify: Reload Apache
  tags: [apache]


- name: Set up Apache vhost config
  ansible.builtin.template:
    src: "apache.conf.j2"
    dest: "{{ apache_server_root }}/conf.d/{{ http_host }}.conf"
  notify: Reload Apache
  tags: [apache]

- name: Remove default site
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ apache_server_root }}/sites-enabled/000-default.conf"
    - "{{ apache_server_root }}/conf.d/welcome.conf"
  notify: Restart Apache
  tags: [apache]

# WordPress Configuration

- name: Download and unpack WordPress 6.8
  unarchive:
    src: https://wordpress.org/wordpress-6.8.tar.gz
    dest: "/var/www/{{ http_host }}"
    remote_src: yes
    creates: "/var/www/{{ http_host }}/wordpress"
  tags: [wordpress]

- name: Set ownership
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    recurse: yes
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
  tags: [wordpress]

- name: Search files in WordPress root path
  ansible.builtin.find:
    paths: "/var/www/{{ http_host }}/wordpress/"
    file_type: file
  register: files
  tags: [wordpress]

- name: Changes permissions to files in WordPress root path
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "0640"
  loop: "{{ files.files }}"
  tags: [wordpress]

- name: Search directories in WordPress root path
  ansible.builtin.find:
    paths: "/var/www/{{ http_host }}/wordpress/"
    file_type: directory
  register: directories
  tags: [wordpress]

- name: Changes permission to directories in WordPress root path
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "0750"
  loop: "{{ directories.files }}"
  tags: [wordpress]

- name: Set up wp-config
  template:
    src: "wp-config.php.j2"
    dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"
  tags: [wordpress]
